### PR TITLE
fix: Broken styling

### PR DESCRIPTION
**Pull request by henryiii**
Partial fix for #5 - disables styling if the structure is wrong.

### CODE REVIEW

**Comment by klieret** [comment]
Cool!! Would you be interesting in pitching that back to https://github.com/carpentries/styles?  This is also in our interest because we keep our ``hsf-styles`` (kind of) synced to theirs and pull from ``hsf-styles`` to all lesson repositories (including this one), so  this would reduce the probability for merge conflicts in the future.

**Comment by henryiii** [comment]
Done, though I can actually revert the stylesheet change if need be, since the workaround I ended up using makes these "normal".

**Comment by henryiii** [comment]
Both fix and C/C++/CMake languages is upstream! Can the hsf-styles be synced?

**Comment by klieret** [comment]
Done! Thanks a lot :)

**Pull request merged**
